services:

##############_____Nextcloud_MariaDB_____##############################

  nxdb:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - internal_network
    volumes:
      - nextcloud-mariadb:/var/lib/mysql
    environment:
      # Set in .env
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # Set in .env
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud_db_user

##############_____NextCloud_App_____##################################

  nextcloud-app:
    image: nextcloud:stable
    container_name: nextcloud-app
    restart: unless-stopped
# Not publishing -> internal netwotrk
#   ports:
#     - 8080:80
# Probably unnecessary - same network, legacy feature ??
    links:
      - nxdb
    networks:
      - internal_network
    volumes:
      - nextcloud:/var/www/html
      # Nextcloud data folder
      # www-data (33:33) user needs rw permissions, other users get r permissions
      # sudo chown -R 33:33 nextcloud
      # sudo chmod -R 744 nextcloud
      - ./nextcloud/data:/var/www/html/data
    environment:
      # Set in .env
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud_db_user
      # Docs: "The default host name used by the mysql command-line client."
      - MYSQL_HOST=nxdb
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.*.* sub.mydomain.com *.mydomain.com mydomain.com
      # HTTPS fix
      - OVERWRITEPROTOCOL=https

##############_____Volumes_and_networks_____###########################

volumes:
  nextcloud:
  nextcloud-mariadb:

networks:
# Existing internal network
  internal_network:
    external: true
