services:

##############_____Navidrome_____######################################

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    networks:
      - internal_network
# Not publishing -> internal netwotrk
#   ports:
#     - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_LOGLEVEL: warn
      # opt out of telemetry
      ND_ENABLEINSIGHTCOLLECTOR: false
    volumes:
      - "./navidrome/navidrome_data:/data"
      - "./navidrome/Music:/music:ro"
      
##############_____Volumes_and_networks_____###########################

networks:
# Existing internal network
  internal_network:
    external: true
