services:

############################
# EXCALIDRAW
############################

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    # ports:
    #   - "3000:80"
    networks:
      - internal_network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug

############################

networks:
  # Existing internal network
  internal_network:
    external: true