services:

############################
# DASHY
############################

  # used only for Glances monitoring widgets
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - ./dashy/conf/dashy_conf.yml:/app/user-data/conf.yml
    networks:
      - internal_network
    # Not publishing -> internal network
    #   ports:
    #     - 8080:8080
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. `id -u` and `id -g`
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

############################

networks:
  # Existing internal network
  internal_network:
    external: true